### ISSUE TITLE
Rewrite it in Rust 🚀

### ISSUE THREAD

**Issue by slendidev** [BowDown097/RRBot#11]
The bot is written in C(ringe)#, rewriting it in Rust (🚀) would provide the following benefits:

 - 🚀Memory🚀safety🚀
 - 🚀Blazingly🚀fast🚀code🚀
 - 🚀Minimal🚀runtime🚀
 - 🚀No🚀Microsoft🚀(penis)🚀
 - 🚀More🚀diverse🚀community🚀
 - 🚀Street🚀cred🚀
 - 🚀Good🚀macro🚀system🚀
 
Also, did I mention it also provides great memory safety (🚀🚀🚀🚀🚀🚀) and speed (⚡⚡)?

![real](https://s3.fission.codes/2022/10/rust_poster.png)

**Comment by KaspianDev** [comment]
safe and stunning

**Comment by BowDown097** [comment]
ywnbaw
