### ISSUE TITLE
write bot in chuck

### ISSUE THREAD

**Issue by Realswitzer** [BowDown097/RRBot#8]
sneed

**Comment by Realswitzer** [comment]
https://chuck.cs.princeton.edu/

**Comment by Realswitzer** [comment]
nvm
![a](https://user-images.githubusercontent.com/39711351/152557071-afd39992-eb69-4f5b-b04c-ea207b7d25a2.png)

**Comment by BowDown097** [comment]
Damn. Super sad. Thank you for the suggestion anyway.
